name: Acceptance Stage

on: [workflow_dispatch]

permissions: write-all

jobs:
  fetch_run_id:
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Get Last Workflow Run ID
        run: |
          response=$(gh api /repos/vaisakhsasikumar/my-electron-app/actions/workflows/nightlyBuild.yml/runs?status=success&per_page=1)
          run_id=$(echo "$response" | jq -r '.workflow_runs[0].id | tonumber')
          echo "RUN_ID=$run_id" >> $GITHUB_ENV

  acceptance_env:
    name: Deploying artifacts to Acceptance Environment and run tests
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs: fetch_run_id
    steps:
      - name: Github checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: brew install jq

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: vaisakhsasikumar/my-electron-app
          run-id: ${{ env.RUN_ID }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install MongoDB
        run: |
          echo "Installing MongoDB..."
          brew tap mongodb/brew
          brew install mongodb-community@6.0

      - name: Start MongoDB
        run: |
          echo "Starting MongoDB..."
          brew services start mongodb/brew/mongodb-community@6.0
          echo "Waiting for MongoDB to be ready..."
          until nc -z localhost 27017; do
            echo "MongoDB is not ready yet, retrying in 5 seconds..."
            sleep 5
          done

      - name: Create test database and collection
        run: |
          echo "Creating test database and collection..."
          mongosh <<EOF
          use test
          db.test.insertMany([
            { name: "test1", value: 1 },
            { name: "test2", value: 2 },
            { name: "test3", value: 3 }
          ])
          EOF

      - name: Set Permissions
        # Allow execute pipeline script
        run: chmod 755 pipeline.sh

      - name: Run pipeline.sh
        run: ./pipeline.sh 

      - name: Stop MongoDB
        run: |
          echo "Stop MongoDB..."
          brew services stop mongodb-community@6.0

  e2e_env:
    name: Deploying artifacts to E2E Environment and run tests
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: macos-latest
    needs: fetch_run_id
    steps:
      - name: Github checkout
        uses: actions/checkout@v4

  acceptance_stage_badge:
    name: Deploying artifacts to E2E Environment and run tests
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [acceptance_env, e2e_env]
    steps:
      - name: E2E Environment badge (Success)
        if: ${{ !contains(needs.*.result, 'failure') }}
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: acceptance_stage
          LABEL: 'Acceptance Stage'
          STATUS: 'Success'
          COLOR: green
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: E2E Environment badge (Failure)
        if: ${{ contains(needs.*.result, 'failure') }}
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: acceptance_stage
          LABEL: 'Acceptance Stage'
          STATUS: 'Failure'
          COLOR: red
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}